HOW IZ I param1 
IF U SAY SO

BTW _____________________________________________________ MAIN
HAI 
SMOOSH str1 AN str2
SUM OF x AN y
DIFF OF x AN y
PRODUKT OF x AN y
QUOSHUNT OF x AN y
BIGGR OF x AN y
SMALLR OF x AN y
BOTH SAEM x AN y
DIFFRINT x AN y
BOTH SAEM x AN BIGGR OF x AN y
BOTH SAEM x AN SMALLR OF x AN y
DIFFRINT x AN BIGGR OF x AN y
DIFFRINT x AN SMALLR OF x AN y
KTHXBYE 